"""empty message

Revision ID: 1a55579351e2
Revises: d5b5a012ba7e
Create Date: 2018-05-05 16:31:45.862107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a55579351e2'
down_revision = 'd5b5a012ba7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('photo', sa.String(length=65535), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'photo')
    # ### end Alembic commands ###
