"""empty message

Revision ID: 313316215b1a
Revises: da5fab8ec3cc
Create Date: 2018-05-04 21:31:56.750139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313316215b1a'
down_revision = 'da5fab8ec3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notified')
    # ### end Alembic commands ###
