"""empty message

Revision ID: d0d73d327e56
Revises: e5ad4e1bc6ab
Create Date: 2018-05-09 15:34:43.951541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d73d327e56'
down_revision = 'e5ad4e1bc6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('photo', sa.String(length=131072), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'photo')
    # ### end Alembic commands ###
