"""empty message

Revision ID: e5ad4e1bc6ab
Revises: 1a55579351e2
Create Date: 2018-05-09 15:32:24.485753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ad4e1bc6ab'
down_revision = '1a55579351e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('photo', sa.VARCHAR(length=65535), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
